### ISSUE TITLE
How to "Open the main WorldEdit GUI from your inventory screen" ?

### ISSUE THREAD

**Issue by mvdw** [Uberi/Minetest-WorldEdit#109]
The tutorial says: "Open the main WorldEdit GUI from your inventory screen." 

Can you explain how that is done? Maybe with a picture?
I see nothing special in the inventory screen...

The chat commands work fine.

**Comment by sfan5** [comment]
Make sure you've enabled the <i>worldedit_gui</i> mod for that world.
You need to press this button:
![bildschirmfoto_2016-03-23_21-35-28](https://cloud.githubusercontent.com/assets/1042418/14000027/89c2c86e-f13f-11e5-87c8-49aa1f41b01e.png)
