### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by SnarkBoojum** [Uberi/Minetest-WorldEdit#115]
Hi,

since august 2013, there has been a ton of commits, but no official release. I would like to update the worldedit package in the Debian distribution, but I'm not sure what I should put in the package...

Thanks!

**Comment by sfan5** [comment]
Generally packaging the current git HEAD should be fine.

If this doesn't harmonize with Debians packaging policies just tell me and I'll go and actually release 1.1 which was planned for a long time already.

**Comment by SnarkBoojum** [comment]
Yes, it would be nice to regularly tag new releases :-P

Thanks!

**Comment by sfan5** [comment]
Here you go: https://github.com/Uberi/Minetest-WorldEdit/releases/tag/1.2

Have fun packaging~

**Comment by SnarkBoojum** [comment]
Thanks!
