### ISSUE TITLE
bad placement of loaded .we schems

### ISSUE THREAD

**Issue by tchncs** [Uberi/Minetest-WorldEdit#120]
Hi there, i need to migrate some buildings from an old, closed server to another one.
When i load a .we file, the region spawns like the following:
````
1 x
x 2
````
becomes:
````
^ ^ ^
b b b >
b b b >
x 2
````

this behavior is some kinda odd, isn't it? 
Or did i get somewthing wrong?

**Comment by tchncs** [comment]
now i am even more confused...

![screenshot_20160717_162734](https://cloud.githubusercontent.com/assets/10698140/16901182/5d2585c8-4c3c-11e6-9ec9-1c0fad26cf14.png)

![screenshot_20160717_123751](https://cloud.githubusercontent.com/assets/10698140/16901170/c7812b30-4c3b-11e6-98fe-f93268a5e308.png)

(define bigger areas wouldn't make any difference, it just spawns outside the selected are so i tried to handly this this way)

**Comment by pyrollo** [comment]
Only position 1 is used as origin. Orientation is always +X +Y +Z

**Comment by Uberi** [comment]
Hi @tchncs,

//load works by loading the entire schematic with position 1 as the origin. As @pyrollo said, position 2 is not used for this command - this is outlined in the documentation [here](https://github.com/Uberi/Minetest-WorldEdit/blob/master/ChatCommands.md#load-file).

If you need to bound a schematic, I recommend creating a blank world and loading it in there, then saving the desired region to a new schematic.
