### ISSUE TITLE
Mapblock chunks indication

### ISSUE THREAD

**Issue by Fixer-007** [Uberi/Minetest-WorldEdit#127]
We need some way to see mapblock borders to work on exactly mapblock basis to avoid problems, graphic indication, or some kind of numbers indication in GUI.

Doable?

**Comment by sfan5** [comment]
I've never needed this, what is it needed for?
And do you mean MapBlocks or MapChunks?

**Comment by Fixer-007** [comment]
mapblocks (16x16x16)

**Comment by wsor4035** [comment]
this has been added to the engine as of 5.5-dev
