### ISSUE TITLE
dig_node with //luatransform does not "pass along" player name

### ISSUE THREAD

**Issue by VanessaE** [Uberi/Minetest-WorldEdit#130]
When executing a //luatransform, and minetest.dig_node() is used therein, the privs of the person running the command (i.e. me, as server admin) are not taken into account - the dig_node() call does nothing if the area is owned by someone besides me.

`2017-03-31 00:36:08: ACTION[Server]:  tried to dig moretrees:apple_tree_trunk at protected position (-273,30,-10)`

Notice there's no username in that error message.  On the other hand, set_node() in that region works fine.

(thankfully, it turned out that I didn't actually NEED to use dig_node() for the thing I was working on)

**Comment by sfan5** [comment]
Nothing WE can do to fix this, but as of https://github.com/minetest/minetest/pull/14505 you can do it correctly in the code you enter for `//luatransform`.
