### ISSUE TITLE
remove /lua chatcommand from worldedit

### ISSUE THREAD

**Issue by HybridDog** [Uberi/Minetest-WorldEdit#134]
See https://forum.minetest.net/viewtopic.php?f=18&t=17601&p=270845#p269633

**Comment by sfan5** [comment]
`//luatransform` can be very useful so I have decided not to remove.
Something I have done however (d6a9b517b58392d9478ac2b6488045b6352fd22b) is remove these from the GUI because it makes no sense to have advanced commands in a "simple" environment.
