### ISSUE TITLE
worldedit_gui breaks inventory of MineClone 2

### ISSUE THREAD

**Issue by Wuzzy2** [Uberi/Minetest-WorldEdit#141]
If you use `worldedit_gui` in MineClone 2, the inventory becomes unusable and buggy.
Both the normal and creative inventory.

The inventory mod of MineClone is `mcl_inventory`.

More information: https://github.com/Wuzzy2/MineClone2-Bugs/issues/284

---

The easy fix would be to simply *not* touch the inventory at all when none of the known inventory mods has been found and simply fall back to the server command.

`mcl_inventory` does not offer any means of modification yet, so that might be the best solution for now.

**Comment by sfan5** [comment]
That code could probably be removed since it didn't work with recent versions of mtg anyway...
(which is why I added `sfinv` support in 610cd9981dbb2649308172936a1c5f626581a4c5)
