### ISSUE TITLE
hide worldedit gui button from normal players

### ISSUE THREAD

**Issue by aerozoic** [Uberi/Minetest-WorldEdit#151]
https://github.com/Uberi/Minetest-WorldEdit/blob/master/worldedit_gui/init.lua#L80

You can hide this button from normal players by adding:
```
show_with = "worldedit",
```
:large_orange_diamond:

**Comment by sfan5** [comment]
No such thing: https://github.com/minetest-mods/unified_inventory/blob/master/doc/mod_api.txt#L38

**Comment by aerozoic** [comment]
Sorry, i didn't realize that was a custom argument from another mod.
:large_orange_diamond:
