### ISSUE TITLE
WorldEdit Commands Don't Work Below Y=0 or Above Y=256 With Cubic Chunks

### ISSUE THREAD

**Issue by blackkittyfreak** [Uberi/Minetest-WorldEdit#157]
Minecraft Version: 1.12.2
WorldEdit Version: 6.1.8

The Cubic Chunks mod is supposed to extend the world height. But when setting blocks or pasting the clipboard with WorldEdit below Y=0 or above Y=256, the blocks outside the standard build limits aren't affected in any way. When the chat gives the number of blocks affected, it includes them in the count, but no change actually occurs outside those boundaries.

**Comment by sfan5** [comment]
You're looking for this bugtracker instead: https://dev.enginehub.org/youtrack/issues/WORLDEDIT

**Comment by blackkittyfreak** [comment]
Thank you.

**Comment by HakkaTjakka** [comment]
You can insert two "floors" (actual: worlds) upon each other. works also with more floors....
The 16 means 16*16, so 256, so one is 10*16 shifted up and the second floor 26*16 (256 higher)
test0 and test1 should contain a level.dat file and region directory.
The first command converts to cubic chunks.
Then the second inserts it into the cubit chunks world dir (current for this batch file, inside the <worldname> dir.
And uses the relocatingConfig.txt file for relocating the created cubic chunks into a existing world.
You also can combine the 2 floors first, by loading one, then shift it up (always 2 separate operations, converting from anvil does not use the relocation tool), load the second into it, the push it into a cubic chunk world.
@ECHO OFF

rem freedom tower / wtc bte 121 projection
rem x=532922*16
rem z=376334*16

java -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M -jar converter.jar --headless -- "srcWorld './TEST0'" "dstWorld './RESULT0'" "inFormat Anvil" "outFormat CubicChunks" "converter Default"
echo move all by -532922 10 -376334 > relocatingConfig.txt
java -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M -jar converter.jar --headless -- "srcWorld './RESULT0'" "dstWorld '.'" "inFormat CubicChunks" "outFormat CubicChunks" "converter Relocating"

java -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M -jar converter.jar --headless -- "srcWorld './TEST1'" "dstWorld './RESULT1'" "inFormat Anvil" "outFormat CubicChunks" "converter Default"
echo move all by -532922 26 -376334 > relocatingConfig.txt
java -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M -jar converter.jar --headless -- "srcWorld './RESULT1'" "dstWorld '.'" "inFormat CubicChunks" "outFormat CubicChunks" "converter Relocating"

pause

exit /b
