### ISSUE TITLE
Middle click with the wand to reset selection

### ISSUE THREAD

**Issue by sbrl** [Uberi/Minetest-WorldEdit#159]
Hello,

I've got a suggestion. Could a middle click when holding the wand tool reset the selection?

I've checked the modding API and it doesn't look like it's possible though. If it's not, what about resetting if you use it when pointing at nothing?

I'm willing to write some code & send a PR here, but wanted an opinion before I go ahead :smiley_cat:

**Comment by sfan5** [comment]
> what about resetting if you use it when pointing at nothing?

That sounds like you'd do it a lot accidentally during normal usage.

**Comment by sbrl** [comment]
Hrm, true. Not sure what other interaction could be bound to it, though. I'd love middle click, but I don't think that the minetest Lua API supports it AFAIKT (though I'm understandably very new to modding, even though I'm not new to programming).

**Comment by sbrl** [comment]
Come to think of it, I might write a separate mod that has a wand with multiple 'modes' to manipulate the selected region.

**Comment by beyondlimits** [comment]
Related Minetest issue: https://github.com/minetest/minetest/issues/4211

:rofl:

**Comment by sfan5** [comment]
Consider reopening when engine adds support.

**Comment by sbrl** [comment]
Maybe an upstream tag would help identify such issues?
