### ISSUE TITLE
.we file format wasting memory

### ISSUE THREAD

**Issue by appgurueu** [Uberi/Minetest-WorldEdit#161]
AFAIK oldest .we is VERY memory inefficent. Please create a smaller format.

**Comment by HybridDog** [comment]
Supposedly it's fixed there: https://github.com/Uberi/Minetest-WorldEdit/pull/61/files#diff-be61291360cf08ee84460573529275e3R74
However, now it seems to not only contain a table called "inventory", but also "fields".
Maybe that function can be used: https://github.com/minetest/minetest/blob/34f940dccae53ac62177d2555c63688fce90519d/doc/lua_api.txt#L3865-L3867

**Comment by appgurueu** [comment]
Still sub-optimal(for instance, storing x,y and z for every node is not the best idea - this can be shortened into one int)

**Comment by HybridDog** [comment]
As far as I know, the .we files are saved in a way that it's easy to manually edit them.
If you want something space-efficient, don't use it.

**Comment by sfan5** [comment]
Experimental branch with better schematic format: [`new_schems`](https://github.com/Uberi/Minetest-WorldEdit/tree/new_schems)
I'm still undecided whether I'll merge this, since .we was never meant to be super space-efficient and nobody has a problem with it in practice.

**Comment by HybridDog** [comment]
It could be possible to extend the compression algorithm from [FLIF](http://flif.info/) to 3D and use this for nodes, param1 and param2 data. This may have a higher compression ration than the mapblock compression in minetest.

**Comment by sbrl** [comment]
Just want to bring another voice to this. I don't know how difficult it is to implement in Lua (though I would be surprised if it hasn't been done before), but what about gzipping it? If the format is space inefficient, then I would guess that it would lend itself to being compressed rather well. There could be a new file extension: e.g. `.wez` or `.we.gz`.

**Comment by HybridDog** [comment]
The FLIF image format has been superseded by FUIF, which has been superseded by [JPEG XL](https://gitlab.com/wg1/jpeg-xl). 
The file-size-relevant part of the Minetest map corresponds to a 3D image with colour palette (the different nodes) and three channels (nodes, param1, param2). The [Meta-Adaptive Near-zero Integer Arithmetic Coding](https://flif.info/spec.html#_maniac_entropy_coding) performs significantly better for indexed images than gzip compression I think. Someone could have a look at the relevant parts of the JPEG XL code (lossless compression, indexed mode) and then write an efficient compression algorithm for the Minetest maps.

**Comment by sfan5** [comment]
I consider this a wontfix.
