### ISSUE TITLE
//scale isn't actually a thing

### ISSUE THREAD

**Issue by GreenXenith** [Uberi/Minetest-WorldEdit#163]
ChatCommands.md lists [`//scale`](https://github.com/Uberi/Minetest-WorldEdit/blob/master/ChatCommands.md#scale-factor) as a valid command, when in reality it certainly is not.
Which is sad because I want to scale an area but stretch doesn't work with negatives or decimals.

**Comment by sfan5** [comment]
fixed in 99fa0ebd752ca9102b775d78953bad858327c2af, interesting how nobody has noticed this in almost 4 years
