### ISSUE TITLE
Feature request:  //clearcut  (in the selected region)

### ISSUE THREAD

**Issue by VanessaE** [Uberi/Minetest-WorldEdit#165]
Such a command would selectively delete nodes in the selection that correspond with some kind of plant, but leaving the underlying terrain untouched, to prepare e.g. a plantlife_modpack-populated piece of terrain for normal construction.

The following commands will do the job, but this way is clearly much more cumbersome, and no doubt a lot slower than a native command:

```lua
//luatransform
	node = minetest.get_node(pos)
	def = minetest.registered_items[node.name]  
	if string.find(node.name, "plant")
	  or string.find(node.name, "cactus")
	  or string.find(node.name, "tree") 
	  or string.find(node.name, "trunk")
	  or (string.find(node.name, "leaves")
	    and not string.find("grass"))
	  or string.find(node.name, "flower")
	  or string.find(node.name, "apple")
	  or string.find(node.name, "vine")
	  or string.find(node.name, "twig")
	  or string.find(node.name, "moss")
	  or string.find(node.name, "bush")
	  or string.find(node.name, "molehill")
	  or string.find(node.name, "pebble")
	  or def and (def.buildable_to
	    or def.drawtype == "plantlike") then
		minetest.remove_node(pos)
	end

//clearobjects
```

Naturally the `//luatransform` command has to be all one line, but I've reformatted it here for readability.  One could probably drop the "plantlike" check, as `buildable_to` covers that for the most part, but paranoia. ;)  The `//clearobjects` command need not be part of this feature.  It's just here because the `//luatransform` command left behind a fair amount of dropped items (saplings, mostly).

The "leaves and not grass" check avoids removal of a few of woodsoil's under-tree "grass with leaves" terrain nodes.

A check to avoid removing water and lava should probably be added, and it may be a good idea to remove unknown/undefined nodes also.

 I guess a way to specify more node names/patterns should be provided, maybe `//clearcut *foo* *bar*` to remove everything in the hardcoded list plus all items bearing "foo" or "bar" in their names.

**Comment by sbrl** [comment]
Perhaps `//weedkiller`, or `//tidy_lawn` would be a better name? :P

**Comment by VanessaE** [comment]
"clearcutting" is the word normally used for felling all the trees and other large flora in an area, in real life, before building on that land, so it seemed like a good choice here, too.

**Comment by sbrl** [comment]
Ah, I see. Good logic!

I didn't know about that terminology. TIL!

**Comment by Niwla23** [comment]
What's about this issue ? Someone working on it?

**Comment by sbrl** [comment]
Not that I'm aware of, @Niwla23. Feel free to do so!

A side note: I'd recommend that the implementation should check against node groups, rather than the node itself as in @VanessaE's `//luatransform` workaround. This will ensure that it's scalable and handles foliage that's added in the future or by mods well. The relevant node group names escape me at the moment though.

**Comment by sfan5** [comment]
![5gpv8lWBgOfX](https://user-images.githubusercontent.com/1042418/78619282-34c82b00-787d-11ea-9355-7670a72ad9f3.gif)
