### ISSUE TITLE
Invalid website linked

### ISSUE THREAD

**Issue by appgurueu** [Uberi/Minetest-WorldEdit#166]
Actually only about this GitHub repo.

In the repo description, the following url is linked : https://forum.minetest.net/viewtopic.php?pid=103341

However, that link seems to be outdated or invalid, as it says I was "not authorised" to read that forum...

Probably link this one : https://forum.minetest.net/viewtopic.php?f=11&t=572 ?

**Comment by sfan5** [comment]
@Uberi 
only he can change the repo description

**Comment by Uberi** [comment]
Fixed!
