### ISSUE TITLE
Allow for an area to be stretched along an axis

### ISSUE THREAD

**Issue by Extex101** [Uberi/Minetest-WorldEdit#168]
![screenshot_20181114_130935](https://user-images.githubusercontent.com/33675971/48512586-b2b20f00-e80e-11e8-8ede-c5ef38f88808.png)
![screenshot_20181114_131018](https://user-images.githubusercontent.com/33675971/48512587-b2b20f00-e80e-11e8-9acf-cd70936e8ef6.png)
Add a stretch region option

Because i need to be able to stretch this
![screenshot_20181114_131202](https://user-images.githubusercontent.com/33675971/48512661-e5f49e00-e80e-11e8-9ece-748482313622.png)

**Comment by sfan5** [comment]
does `//stretch 1 2 1` not do what you need?

**Comment by Extex101** [comment]
I tried using stretch but all it did was stretch the location of //1 and //2
Oh I did //stretch 0 2 0
Nvm thanks

**Comment by Extex101** [comment]
All you need now is a //squish
