### ISSUE TITLE
//set twice in a row without changing region crashes server

### ISSUE THREAD

**Issue by TheCompGeek** [Uberi/Minetest-WorldEdit#171]
Discovered this setting some clay. Node name `bakedclay:white` to be exact. Anyways...

If you select a region using `//1` and `//2` or use the WE helper mod, followed by using `//set <nodename>` twice in a row without changing the region, it crashes the server.

1)Select region
2)`//set <nodename>`
3)`//set <nodemane>`
4)Server quits pinging out, all clients time out
5)Server disconnects from IRC with a 121 second timeout
6)Server comes back online 38 seconds later

IDK how old this bug is, but it's on the more sever end of things, as an inexperienced user can inadvertently crash the server, which could lead to major map corruption.

**Comment by HybridDog** [comment]
I cannot reproduce this. Do you have the log messages when the crash happens?
