### ISSUE TITLE
worldedit.set() inconsistent when using player position

### ISSUE THREAD

**Issue by discon-nected** [Uberi/Minetest-WorldEdit#172]
I have the following code which should simply set a mese lamp under the player's feet...
```
minetest.register_chatcommand("light", {
	params = "",
	description = "",
	func = function(name, param)
		local player = minetest.get_player_by_name(name)
		if not player then
			return false, "Player not found"
		end
		--player:getpos()
    local pos = player:get_pos()
    local npos1 = {x = pos.x, y = pos.y - 1, z = pos.z}
    local npos2 = {x = pos.x, y = pos.y - 1, z = pos.z}
    minetest.chat_send_all("x = " .. pos.x .. ", y = " .. pos.y - 1 ..", z = " .. pos.z)
    worldedit.set(npos1, npos2, "default:meselamp")
		return true
	end,
})
```
What is strange is that minetest.chat_send_all  prints the player's coordinates correctly, but the mese lamp is placed between 1 and 30 blocks away from the player. If the player remains in the same place the block is consistently placed in the same location. Move over 1 block and the mese lamp is placed in an entirely different location, not relative the player's movement. x,y, and z offsets from the player. When I use `minetest.place_node({x=pos.x, y=pos.y, z=pos.z}, {name="default:meselamp"})` instead,  the placement is accurate every time.

**Comment by sfan5** [comment]
Couldn't reproduce and I don't see why this would happen at all.
