### ISSUE TITLE
Cannot clear objects in large region

### ISSUE THREAD

**Issue by rileyweber13** [Uberi/Minetest-WorldEdit#185]
# Expected Behavior:
 1. I select a large region
 1. I execute the command '//clearobjects'
 1. the objects are cleared

# Actual behavior:
Between steps 2 and 3, the game freezes for a very short amount of time and then crashes with this error message:

![20190920_180140](https://user-images.githubusercontent.com/25539219/65361319-22ccb680-dbd1-11e9-97d8-a31d0e8ca283.png)

(as far as I know, there isn't a way to copy and paste this raw text... but if there is a way, please tell me and I will replace the image with text)

**Comment by rileyweber13** [comment]
I don't have a lot of experience in lua but if I get the chance I'll look at the code this weekend. Help is appreciated if anyone has more free time than me :)

**Comment by sfan5** [comment]
Technically a bug with the Minetest engine, since it's returning that error for a valid API call.

However, the problem here is elsewhere and the solution is going to be disappointing:
You're asking too much of worldedit and/or the engine, <i>just don't</i> try to `//clearobjects` an area this large.

**Comment by rileyweber13** [comment]
Thanks for the info. Unless lua (or the implementation of integer used by minetest) simply doesn't support numbers this large, I don't understand how I am asking too much? Can you help me understand why this is unreasonable?

I am happy to open an issue at minetest instead of here, but I thought I'd finish this discussion first. No point opening an issue if what I'm asking is not possible without drastic code changes.

**Comment by sfan5** [comment]
As WorldEdit said your selected area has 20802080052 nodes, keeping this area loaded at once would take <b>at least</b> 116 GB of RAM. I doubt you have that much and even if you did, the engine would most likely not handle that much at once.

Maybe you want `/clearobjects` instead, whichc an clear objects in your entire world just fine without these constraints.

**Comment by rileyweber13** [comment]
gotcha, so minetest loads the entire area when you try to edit it?

**Comment by sfan5** [comment]
Yes. WorldEdit does that, since it needs to.

**Comment by rileyweber13** [comment]
Is it not possible to load and edit the nodes in chunks of, say, 100x100x100 at a time?

**Comment by sfan5** [comment]
Yes, however working with areas so big that they require to be split up as not to crash the engine is not an usecase I plan to support.
