### ISSUE TITLE
Import minecraft schematics

### ISSUE THREAD

**Issue by AFCMS** [Uberi/Minetest-WorldEdit#196]
It would be cool to can convert and when, import Minecraft schematics with a command.
For converting, there may be a conversion table which can change depending on the game.

**Comment by sfan5** [comment]
This is out of scope for WorldEdit itself, but writing a schematic converter is something I planned to do for a while.

If you're looking for existing solutions there's e.g. this: https://forum.minetest.net/viewtopic.php?f=12&t=13709

**Comment by AFCMS** [comment]
When is planned converter ?
