### ISSUE TITLE
Set Param2 button

### ISSUE THREAD

**Issue by NathanSalapat** [Uberi/Minetest-WorldEdit#202]
With the advent of all the new hardware coloring options it seems like it would be a good idea to have a button in the GUI to set the param2 value. I see there is already a chat command for it, and am willing to create a PR to add a button to the GUI.

I actually discovered all this while working on a game that include WE. I have the button implemented in my game and have had no issues with it.

**Comment by sfan5** [comment]
Sure, I would appreciate a PR.

**Comment by NathanSalapat** [comment]
PR #203
