### ISSUE TITLE
Implement a calculation time and cost estimate, a scheduler, and a watchdog timer

### ISSUE THREAD

**Issue by Baigle** [Uberi/Minetest-WorldEdit#208]
WE often can crash a server on simple rotation or other operations like moving or copying. Adding a scheduler would allow periodic calculation that does not severely impact server performance, a watchdog timer is needed to undo or prevent difficult operations from crashing a server, and a calculation estimate or adjustment would be nice for operators to use if they want it done more quickly or slower.

Additionally, operating on compressed data can lower the footprint of computational and memory operations.

**Comment by sfan5** [comment]
I'm not aware of any crash bugs one those operations.
Unless of course you are running out of RAM, in which case it would be beneficial if WorldEdit could automatically split the operation (maybe that's what you mean).

> Additionally, operating on compressed data can lower the footprint of computational and memory operations.

Not really. Compression also takes CPU time so it can't be faster _at the same time_ as consuming less memory.
