### ISSUE TITLE
Crash with new minetest.serialize format

### ISSUE THREAD

**Issue by loosewheel** [Uberi/Minetest-WorldEdit#211]
The saves are in the new minetest.serialize (I'm using 5.6.0) format but deserialize_workaround in worldedit/serialization.lua doesn't use minetest.deserialize, but its own method which can't handle the new format. It pulls the contents of the table from the string and constructs each inner table. The new minetest format creates variables of common strings and uses them in the returned table. Because these variable names are missing most of the inner tables strings are resulting in nil.

I did the following and it seems to work. It just gets the variable code (before "return") and adds it to the beginning of each inner table call to minetest.deserialize. I didn't robustly test it and didn't check for backward compatability (although it should be, prior versions before return is just an empty string).

```
local function deserialize_workaround(content)
	local nodes
	if not jit then
		nodes = minetest.deserialize(content, true)
	else
		-- XXX: This is a filthy hack that works surprisingly well
		-- in LuaJIT, `minetest.deserialize` will fail due to the register limit
		nodes = {}
		local variables = (content:find("return", 1, true) and content:sub(1, (content:find("return", 1, true)) - 1)) or ""
		content = content:gsub("^%s*return%s*{", "", 1):gsub("}%s*$", "", 1) -- remove the starting and ending values to leave only the node data
		-- remove string contents strings while preserving their length
		local escaped = content:gsub("\\\\", "@@"):gsub("\\\"", "@@"):gsub("(\"[^\"]*\")", function(s) return string.rep("@", #s) end)
		local startpos, startpos1 = 1, 1
		local endpos
		while true do -- go through each individual node entry (except the last)
			startpos, endpos = escaped:find("},%s*{", startpos)
			if not startpos then
				break
			end
			local current = content:sub(startpos1, startpos)
			local entry = minetest.deserialize(variables .. "return " .. current, true)
			table.insert(nodes, entry)
			startpos, startpos1 = endpos, endpos
		end
		local entry = minetest.deserialize(variables .. "return " .. content:sub(startpos1), true) -- process the last entry
		table.insert(nodes, entry)
	end
	return nodes
end
```
Edited: forgot last inner table after while loop.

**Comment by sfan5** [comment]
See abc9efeeb8cccb3e23c055414941fed4a9871b9a which gets rid of the crash for small (most?) schematics.

> I didn't robustly test it and didn't check for backward compatability

It would indeed fail if you have any node or metadata that contains the substring 'return'.
But the idea sounds usable, thanks.

**Comment by loosewheel** [comment]
I don't know if there is any intention to use the above method, but I don't think it would be a good idea. This was really intended to demonstrate the problem, not as a fix. Its not bad code and a good idea. Its bad code and a bad idea.

I've not used WE, and don't know how to use it. I just needed it to test 1 thing, so I just got it running to do that.

As far as accurately determining the end of the string code, the line 'local escaped = ...' replaces the contents of strings with the @ character. This may be reliable to search for "return". But more needs to be done because generally the first node table is malformed, because the input is not as expected.

As far as compiling and constructing the strings for every node table, this would be a huge overhead. Especially on large schematics. I would probably use an environment table to reconstruct the data. That way the process would have little more overhead than just calling minetest.deserialize on the source.

**Comment by sfan5** [comment]
> Its not bad code and a good idea. Its bad code and a bad idea.

The whole workaround for the sake of LuaJIT is already bad idea and it's already there. But what's the alternative?

**Comment by sfan5** [comment]
I understood that you were calling the entire string-splitting/separate serialization a bad idea, but that doesn't seem to be it.

I'm aware that taking the first code 1:1 and only fixing up minor details would have (not only) performance issues. I was planning some sort of batching for the duplicated local variables anyway.

**Comment by appgurueu** [comment]
Same issue: https://github.com/mt-mods/pipeworks/issues/39#issuecomment-1212769926

I'm starting to think that it probably was a bad idea to use named references on LuaJIT. If we switch back to a reference table and numbered references we can free up plenty of register slots (at the cost of slightly larger filesize). Will make a PR.
