### ISSUE TITLE
Fix lights after placing a schematic

### ISSUE THREAD

**Issue by Panquesito7** [Uberi/Minetest-WorldEdit#214]
### Description

After placing a schematic in WorldEdit with code functions, the lights aren't fixed automatically and you have to manually fix them.
It'd be great if those are automatically fixed _after_ placing the schematic. This would make the process much easier and better for users as well.

What do you think? Thanks. 🙂

**Comment by sfan5** [comment]
Usually placing a schematic _should not_ break the lighting in that area.
By "code functions" are you referring to the API? Or in-game commands?

**Comment by Panquesito7** [comment]
Yes, the API. IIRC, in-game commands work fine, though.

**Comment by sfan5** [comment]
In the case of the API I would put the responsibility on the user, `worldedit.fixlight` exists.
