### ISSUE TITLE
Compatible with MineClone2?

### ISSUE THREAD

**Issue by Paelor** [Uberi/Minetest-WorldEdit#218]
Hello, wanted to know if this was compatible with latest MineClone2? I've been wanting to start creating complete the monument (CTM) "maps" using the MineClone2 game, but really need a world editor like this. If this version isn't compatible could a fork be made to support latest MineClone2?

**Comment by sfan5** [comment]
The only game dependency WorldEdit has is for worldedit_gui to make it function.
You can use the rest of it with any game
