### ISSUE TITLE
Crash on loading Schem files (5.7.0)

### ISSUE THREAD

**Issue by KingBBQ** [Uberi/Minetest-WorldEdit#220]
similar to #212 

Log from the Minetest-Server:

```
minetest_zfn_museum    | 2023-06-06 13:15:16: ACTION[Main]: Server: Shutting down
minetest_zfn_museum    | 2023-06-06 13:15:16: ERROR[Main]: ServerError: AsyncErr: Lua: Runtime error from mod '' in callback on_playerReceiveFields(): /config/.minetest/mods/worldedit_commands/init.lua:1507: attempt to concatenate local 'count' (a nil value)
minetest_zfn_museum    | 2023-06-06 13:15:16: ERROR[Main]: stack traceback:
minetest_zfn_museum    | 2023-06-06 13:15:16: ERROR[Main]: 	/config/.minetest/mods/worldedit_commands/init.lua:1507: in function 'func'
minetest_zfn_museum    | 2023-06-06 13:15:16: ERROR[Main]: 	/config/.minetest/mods/worldedit_commands/init.lua:55: in function 'func'
minetest_zfn_museum    | 2023-06-06 13:15:16: ERROR[Main]: 	/usr/share/minetest/builtin/profiler/instrumentation.lua:108: in function 'func'
minetest_zfn_museum    | 2023-06-06 13:15:16: ERROR[Main]: 	/config/.minetest/mods/we_undo/init.lua:46: in function 'func'
minetest_zfn_museum    | 2023-06-06 13:15:16: ERROR[Main]: 	/config/.minetest/mods/worldedit_gui/functionality.lua:141: in function 'execute_worldedit_command'
minetest_zfn_museum    | 2023-06-06 13:15:16: ERROR[Main]: 	/config/.minetest/mods/worldedit_gui/functionality.lua:845: in function 'func'
minetest_zfn_museum    | 2023-06-06 13:15:16: ERROR[Main]: 	/usr/share/minetest/builtin/profiler/instrumentation.lua:108: in function </usr/share/minetest/builtin/profiler/instrumentation.lua:101>
minetest_zfn_museum    | 2023-06-06 13:15:16: ERROR[Main]: 	/usr/share/minetest/builtin/game/register.lua:446: in function </usr/share/minetest/builtin/game/register.lua:432>
```
Sample file:

[06-4.we.zip](https://github.com/Uberi/Minetest-WorldEdit/files/11663786/06-4.we.zip)

- Minetest Server 5.7.0, running in Docker
- Minetest Client 5.7.0 running on Mac 

Initially I had the problem with more files, figured out it was some blocks, that had similar names in 2 Mods (more_blocks...) 
But this one is cant be fixed with mods:

- I am in the same world
- I mark it
- save it
- try to load it again 
- chrashes right away (logfile see above...)

I am using the latest version from this git repo (most recent branch, not the zip release)

**Comment by sfan5** [comment]
WorldEdit will now no longer crash when attempting to load the schematic.
It will however still fail. There are some complex reasons with LuaJIT and format changes that mean you can't load this schematic currently.

**Comment by KingBBQ** [comment]
Thanks for your quick Help! Do you have  any tips for me how to export / import this part of the world? We did workshops at schools and now want to put all buildings of the students together in one big Museum world (Zukunftsnacht.de). Can I use a different size of  block to copy? Can I disable certain mods? Any other tips how the copy between worlds can be achieved?

**Comment by sfan5** [comment]
You can try [`//mtschemcreate`](https://github.com/Uberi/Minetest-WorldEdit/blob/master/ChatCommands.md#mtschemcreate-file) which uses engine schematics. These however do not save metadata which means some nodes may not "work" after import.
