### ISSUE TITLE
//clearobjects not clears objects

### ISSUE THREAD

**Issue by Valentina-W** [Uberi/Minetest-WorldEdit#230]
Repro:

> Minetest 5.7.0
> worldedit latest content db release
1. drop item
2. place markers around item with wand or //1 and //2
3. Sende //clearobjects

Wrong: chatmessage 0 objects cleared, object still present
Expected: object removed, chatmessage tells correct number

**Comment by sfan5** [comment]
fixed by 8f60e6f, thanks for the report.
