### ISSUE TITLE
Unable to load saved things

### ISSUE THREAD

**Issue by Alatarius** [Uberi/Minetest-WorldEdit#231]
Just as the title says, I saved many things successfully and tried to use them in a new world but it always gives me the error "Unable to load [saved name]".

I am using the most recent version of mt and playing minetest_game. All world gen options and mods are identical in worlds.

**Comment by sfan5** [comment]
Can you post an example file that won't load?

**Comment by Alatarius** [comment]
> Can you post an example file that won't load?

I tried to copy the schems folder to my new world and now I get this error and world crashes on startup and returns to the main menu:

AsyncErr: Lua: Runtime error from mod 'ebiomes' in callback on_playerReceiveFields(): Unknown node: poisonivy:climbing
stack traceback:
	[C]: in function '__index'
	D:\Games\Minetest\bin\..\builtin\common\item_s.lua:229: in function <D:\Games\Minetest\bin\..\builtin\common\item_s.lua:228>
	[C]: in function 'add_node'
	D:\Games\Minetest\bin\..\mods\we_undo\init.lua:1073: in function 'add_node'
	...netest\bin\..\mods\worldedit\worldedit/serialization.lua:257: in function 'we_deserialize'
	D:\Games\Minetest\bin\..\mods\we_undo\init.lua:1080: in function 'deserialize'
	...netest\bin\..\mods\worldedit\worldedit_commands\init.lua:1497: in function 'func'
	...netest\bin\..\mods\worldedit\worldedit_commands\init.lua:55: in function 'func'
	D:\Games\Minetest\bin\..\mods\we_undo\init.lua:46: in function 'func'
	...st\bin\..\mods\worldedit\worldedit_gui/functionality.lua:141: in function 'execute_worldedit_command'
	...st\bin\..\mods\worldedit\worldedit_gui/functionality.lua:845: in function <...st\bin\..\mods\worldedit\worldedit_gui/functionality.lua:835>
	D:\Games\Minetest\bin\..\builtin\game\register.lua:446: in function <D:\Games\Minetest\bin\..\builtin\game\register.lua:432>

**Comment by sfan5** [comment]
You need to have the same mods installed on the world you are loading the schematic in as in the world it was created from.
Improving the error message for this is an open point (#210).

**Comment by Alatarius** [comment]
also when loading other things sometimes it makes the load way off-center

e.g.

-------------------------
|                                    |
|                                    |
|                                    |
|                                    |
|                                    |
--------------------------
(pos 1)
this is how it saved but when loaded it loads like this

-------------------------
|                                    |
|                                    |
|                                    |
|                                    |
|                                    |
--------------------------
                                                                                                        (pos1)


> You need to have the same mods installed on the world you are loading the schematic in as in the world it was created from. Improving the error message for this is an open point (#210).

They are the same. That's the strange part.

**Comment by Alatarius** [comment]
When I saved my build I have the entire region around the build but when it loaded it did this:

![WE Load error](https://github.com/Uberi/Minetest-WorldEdit/assets/101660302/d98b8755-498c-484c-a653-04b16850a499)

**Comment by Alatarius** [comment]
Just found a new error. WE won't save an entire build. It's a 3-story mansion of around 50000 nodes and we only saves about 1/5 of that.

![WE save error](https://github.com/Uberi/Minetest-WorldEdit/assets/101660302/98c1f197-d07f-4496-86c4-44804235d300)

**Comment by sfan5** [comment]
> They are the same. That's the strange part.

They're not or this wouldn't be happening.
Other causes can be different mod versions or mods somehow differently configured.

> Just found a new error. WE won't save an entire build. It's a 3-story mansion of around 50000 nodes and we only saves about 1/5 of that.

Are you going off the numbers alone? Air nodes are not saved so it's natural for the actual number to be less than the area volume.
