### ISSUE TITLE
Text of signs is not exported / imported with mtschemcreate / mtschemplace

### ISSUE THREAD

**Issue by Zacrain** [Uberi/Minetest-WorldEdit#232]
When a region marked for export via `mtschemcreate` contains signs which have text set to it, the text is vanished when importing the schematic via `mtschemplace`.

I have this problem with Minetest 5.7.0 and the up to date release of WorldEdit.

**Comment by sfan5** [comment]
This is a format limitation, the `mts` format does not support metadata.
