### ISSUE TITLE
README.md: The link to the Minetest forums does not work

### ISSUE THREAD

**Issue by YuGiOhJCJ** [Uberi/Minetest-WorldEdit#241]
In the file README.md, the link to the Minetest forums does not work.
URL: https://forum.minetest.net/viewtopic.php?id=572
Result: "The requested topic does not exist.".
Line of code: https://github.com/Uberi/Minetest-WorldEdit/blob/b90eeb1e6882a779f3dd5226a7d097be0397dc46/README.md?plain=1#L5

**Comment by Panquesito7** [comment]
`id` should be changed to `t` and it should work properly.

**Comment by sfan5** [comment]
The link used to be valid for years but it appears the redirection logic in the forum software was lost with an upgrade.
