### ISSUE TITLE
crash when hiding/restoring a region

### ISSUE THREAD

**Issue by VanessaE** [Uberi/Minetest-WorldEdit#29]
terminate called after throwing an instance of 'ServerError'
  what():  ...vanessae_game/mods/worldedit/worldedit/visualization.lua:138: bad 
argument #4 to 'add_node' (string expected, got nil)
stack traceback:
        [C]: in function 'add_node'
        ...vanessae_game/mods/worldedit/worldedit/visualization.lua:138: in func
tion 'restore'
        ...vanessae_game/mods/worldedit/worldedit_commands/init.lua:911: in func
tion 'func'
        ...ssae_game/mods/worldedit/worldedit_gui/functionality.lua:575: in func
tion 'on_select'
        ...ames/vanessae_game/mods/worldedit/worldedit_gui/init.lua:220: in func
tion <...ames/vanessae_game/mods/worldedit/worldedit_gui/init.lua:210>
        /usr/local/share/minetest/builtin/misc_register.lua:330: in function </u
sr/local/share/minetest/builtin/misc_register.lua:318>
/home/minetest/Scripts/minetestserver-survival.sh: line 25: 25671 Aborted

**Comment by sfan5** [comment]
maybe fixed by bb8456b71119ca6303b9e9706829a84dc7f81ab3

please reopen if it happens again
