### ISSUE TITLE
Region Selection Improvements

### ISSUE THREAD

**Issue by spillz** [Uberi/Minetest-WorldEdit#37]
I had a few thoughts about making region selection a bit more user friendly.

I would like to add the following types of commands (thought not necessarily with these names)

`//setactivenode` -- select the active region node (1 or 2)
`//toggleactivenode` -- switch to the other region node
`//setactivefore` -- move the active node n units (1 by default) in the nearest horizontal direction from the camera (NHDC)
`//setactiveback` -- move the active node n units (1 by default) backward NHDC
`//setactiveleft` -- move the active node n units (1 by default) left NHDC
`//setactiveright` -- move the active node n units (1 by default) right NHDC
`//setactiveup` -- move the active node up n units  (1 by default) (y axis)
`//setactivedown` -- move the active node down n units  (1 by default) (y axis)

Then I am going to try to patch minetest to allow binding commands to shortcut keys as I suggested here: https://forum.minetest.net/viewtopic.php?id=8611

It could be nice to have a set of shortcuts bound to the keypad, like 
Up `//setactivefore`
Down `//setactiveback`
Left `//setactiveleft`
Right `//setactiveright`
PgUp `//setactiveup`
PgDn `//setactivedown`
Ins `//toggleactivenode`

(Could also imagine using shift+arrow keys for moving the inactive anchor, ctrl+arrow for moving both anchors at once, ctrl+click to set anchors without needing to set them etc)

Is this worth pursuing in your opinion?

**Comment by sfan5** [comment]
something like this was added with #118
