### ISSUE TITLE
Cuboid manipulation chat commands

### ISSUE THREAD

**Issue by danierukun** [Uberi/Minetest-WorldEdit#69]
Hi, I'm working on adding cuboid manipulation commands such as outset, inset, etc. To match those in the minecraft version of worldedit. I already have some working. I was wondering if you would be interested in accepting the changes.

I already have:
 - Outset
 - Inset
 - Shift
 - Expand (WIP)

The code still needs some cleaning, but it shouldnt take too much time.

**Comment by ShadowNinja** [comment]
Sounds useful.
