### ISSUE TITLE
having trouble using .mts files

### ISSUE THREAD

**Issue by MT-Modder** [Uberi/Minetest-WorldEdit#77]
For more info see https://github.com/minetest/minetest/issues/2481. I'm not sure if this is a mod bug or an engine bug so... I reported it here and in the engine repository.

**Comment by Uberi** [comment]
Seems to be an engine issue, though I'm not discounting the possibility of it being the way WE is using the API. In any case, we'll need people more experienced with the file format to see what's wrong.

Would it be possible to upload the .mts file somewhere for debugging?

**Comment by MT-Modder** [comment]
Yeah it happens with every file so...Here's a file:https: //www.dropbox.com/s/g18laq6m18ga4zn/test.mts?dl=0

**Comment by MT-Modder** [comment]
I quickly wrote a mod to create schematics and I had the same issue so I think this is an engine issue. Either ```minetest.create_schematic()``` is broken or ```minetest.register_decoration()``` is.
