### ISSUE TITLE
//stack is horrendously slow

### ISSUE THREAD

**Issue by VanessaE** [Uberi/Minetest-WorldEdit#81]
Make a region of 50 x 5 x 50
Select it
//stack y 10

...the whole thing runs for a while, says it's stacked N nodes, then continues to spin the CPU at 100% and never finishes.

Meanwhile, //copy seems to work fine for the same amount of data - just a matter of several seconds.  The slowness is to the point that, even for a relatively small area (say 10x5x5 nodes) I can //copy the structure repeatedly (with increasing coordinates) and get the job done faster than using //stack to do the same thing.

**Comment by sfan5** [comment]
This is likely caused by `worldedit.stack` using minetest.after(0, ...) to prevent the server from freezing while doing it's job.

**Comment by HybridDog** [comment]
>This is likely caused by worldedit.stack using minetest.after(0, ...) to prevent the server from freezing while doing it's job.

l made a mod for this, you could use it if it's installed and if not, stack all at once.
https://github.com/HybridDog/function_delayer

**Comment by HybridDog** [comment]
@VanessaE worldedit.copy doesn't use vmanip, l edited it and it works fairly fast, l haven't tested //stack without vmanip

**Comment by sfan5** [comment]
cc897150f2721b4163ff8516bc925e51bfdafab9
