### ISSUE TITLE
upsidedown pyramid not working well

### ISSUE THREAD

**Issue by cornernote** [Uberi/Minetest-WorldEdit#83]
It seems to place a couple of levels, then it places the rest of them up higher...

![image](https://cloud.githubusercontent.com/assets/51875/8974850/e02845fc-36b5-11e5-9495-8ff2e6527edb.png)

**Comment by sponce** [comment]
This is addressed in this pull request : https://github.com/Uberi/Minetest-WorldEdit/pull/88

**Comment by sfan5** [comment]
2e2fcfdfa2f5f9b15951d6f149c3c1d72bedf1a6
