### ISSUE TITLE
Unified Inventory API changes

### ISSUE THREAD

**Issue by VanessaE** [Uberi/Minetest-WorldEdit#91]
A small change was made (by me :smile: ) to Unified Inventory's API today that sort-of affects this mod, namely the "Worldedit GUI" button.  When UI's "lite" mode is enabled globally, it can be switched back to "full" mode on a per-user basis.  As a consequence, buttons are now hidden in "lite" mode by setting a field in the button definition:

https://github.com/minetest-technic/unified_inventory/blob/master/register.lua#L46

By default, the button will be visible/active in either mode (which matches the previous behavior of this button anyway).

**Comment by sfan5** [comment]
Matches previous behaviour, nothing to be done.
