### ISSUE TITLE
//move is horribly slow

### ISSUE THREAD

**Issue by VanessaE** [Uberi/Minetest-WorldEdit#96]
I'm finding that `//move` is horribly slow.  For example, consider the following structure measuring about 56x50x200 (so ~560'000 nodes, of which around 100'000 are not air):

![image](https://cloud.githubusercontent.com/assets/1733537/11888388/c78cff56-a50a-11e5-810d-6941eca6afc8.png)

Moving this thing by 25 meters in the -X direction took 18 minutes with Minetest built in Debug mode (I did not try it in Release mode).  The majority of that time was spent with the engine really not using much CPU (20% to 70% of one core, largely variable), until the very end, where it spiked to 100% for about one minute before the server finally "woke up" and showed me the result of the move.

The move was successful, despite the long wait.

It's slow enough that, suppose I `//load` a schematic... beyond some size (not sure how big), it's faster to erase the building with `//set air`, do `//1` at a new target, and `//load` the schematic again, than it is to just `//load` it once and `//move` it where it needs to go.

**Comment by pinkysnowman** [comment]
I to notice that.  Also //stk (stack)   is slower than anything.

**Comment by sfan5** [comment]
f39a8e264dab33f9b8df120aa0289b0c017bc1e2
