### ISSUE TITLE
Putting //2 too far from //1 (or vice versa) leads to crash

### ISSUE THREAD

**Issue by VanessaE** [Uberi/Minetest-WorldEdit#97]
One of my admins was doing some worldediting, and inadvertently set pos1 too far from pos2.  It is the result of having set pos1 and pos2 in a smaller area, then teleporting far away, and setting pos1 again (via a punch) without first having done a //reset.  The two markers were about 10km apart at that point.

Here's the log excerpt from the crash:

```
2015-12-27 18:52:32: ERROR[Main]: ServerError: Lua: Runtime error from mod 'extranodes' in callback node_on_punch(): std::bad_alloc
2015-12-27 18:52:32: ERROR[Main]: stack traceback:
2015-12-27 18:52:32: ERROR[Main]:       [C]: in function 'read_from_map'
2015-12-27 18:52:32: ERROR[Main]:       ...mbuilder_game/mods/worldedit/worldedit_commands/mark.lua:68: in function 'mark_region'
2015-12-27 18:52:32: ERROR[Main]:       ...mbuilder_game/mods/worldedit/worldedit_commands/mark.lua:25: in function 'mark_pos1'
2015-12-27 18:52:32: ERROR[Main]:       ...mbuilder_game/mods/worldedit/worldedit_commands/init.lua:253: in function 'callback'
2015-12-27 18:52:32: ERROR[Main]:       /usr/share/minetest/builtin/game/item.lua:418: in function </usr/share/minetest/builtin/game/item.lua:411>
```

(extranodes is a component of technic, and probably isn't actually related).

**Comment by Uberi** [comment]
Hmm, what's the memory usage like? Looks a bit like an out of memory error.

**Comment by VanessaE** [comment]
At the time of the crash, there was a little over 4 GB total memory in use, spread across 14 Minetest  server instances, plus a few hundred megs used by the underlying OS and its applications.  The server has 32 GB of physical RAM plus 512 MB of swap.  The server instance that crashed generally doesn't use more than several hundred megs, at worst.  Dreambuilder isn't exactly light on RAM usage. :smile:

**Comment by Uberi** [comment]
That seems quite possible - perhaps it would be best to stop using those entities when the area gets too large... adding multiple entities would probably be too slow for something like a 10km area.

**Comment by VanessaE** [comment]
True on both counts, though using several for a smaller area might be a good idea; for example, as I am writing this, I'm dealing with a ~165x60x165 area that I selected via //1 and //2.  The corner markers are there, but the checkered sides never appeared.

(meanwhile, that area is taking an ice age to //save out)

**Comment by ShadowNinja** [comment]
@VanessaE: Yes, it's loaded into a big table before writing.  It could brobably be done in chunks, but that would likely require a new format.  LuaJIT has a ~1GiB memory limit, and a low constant limit.  Also, Lua (at least 5.3) performs much, much faster than LuaJIT at some operations (something like 50x faster for building a bunch of strings and adding them to a table IIRC).  So try Lua and see if that helps.

**Comment by VanessaE** [comment]
Why would it require a new (file) format?  Anyway plain Lua is a non-starter, as LuaJIT is still faster for most other common operations.
